export const characters = [
  {
    id: 1,
    name: "Jonathan Joestar",
    stand: "Hamon",
    first_appearance: "Phantom Blood",
    fighting_style: "Martial Arts",
    notable_enemy: "Dio Brando",
    personality: "Noble and honorable",
  },
  {
    id: 2,
    name: "Dio Brando",
    stand: "The World",
    first_appearance: "Phantom Blood",
    fighting_style: "Vampiric Power",
    notable_enemy: "Jonathan Joestar",
    personality: "Cunning and manipulative",
  },
  {
    id: 3,
    name: "Joseph Joestar",
    stand: "Hermit Purple",
    first_appearance: "Battle Tendency",
    fighting_style: "Clever and trickery-based",
    notable_enemy: "Straizo",
    personality: "Quick-witted and humorous",
  },
  {
    id: 4,
    name: "Jotaro Kujo",
    stand: "Star Platinum",
    first_appearance: "Stardust Crusaders",
    fighting_style: "Strong, direct combat",
    notable_enemy: "Dio Brando",
    personality: "Stoic and serious",
  },
  {
    id: 5,
    name: "Kakyoin Noriaki",
    stand: "Hierophant Green",
    first_appearance: "Stardust Crusaders",
    fighting_style: "Precision and agility",
    notable_enemy: "Dio Brando",
    personality: "Loyal and reserved",
  },
  {
    id: 6,
    name: "Polnareff Jean-Pierre",
    stand: "Silver Chariot",
    first_appearance: "Stardust Crusaders",
    fighting_style: "Fast-paced sword fighting",
    notable_enemy: "Dio Brando",
    personality: "Brave and chivalrous",
  },
  {
    id: 7,
    name: "Avdol Muhammad",
    stand: "Magician's Red",
    first_appearance: "Stardust Crusaders",
    fighting_style: "Fire-based attack",
    notable_enemy: "Dio Brando",
    personality: "Strong and wise",
  },
  {
    id: 8,
    name: "Rohan Kishibe",
    stand: "Heaven's Door",
    first_appearance: "Diamond is Unbreakable",
    fighting_style: "Psychic manipulation through writing",
    notable_enemy: "Kira Yoshikage",
    personality: "Arrogant but artistic",
  },
  {
    id: 9,
    name: "Giorno Giovanna",
    stand: "Gold Experience",
    first_appearance: "Golden Wind",
    fighting_style: "Life-manipulating power",
    notable_enemy: "Diavolo",
    personality: "Ambitious and determined",
  },
  {
    id: 10,
    name: "Bruno Bucciarati",
    stand: "Sticky Fingers",
    first_appearance: "Golden Wind",
    fighting_style: "Spatial manipulation and speed",
    notable_enemy: "Diavolo",
    personality: "Loyal and empathetic",
  },
];
